# Generated by Django 3.2.25 on 2025-10-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ingredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredientes',
            new_name='ingredients',
        ),
    ]
